# Generated by Django 5.0.14 on 2025-11-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen_dashboard', models.ImageField(upload_to='dashboard_images/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_tarea', models.CharField(choices=[('clasificacion', 'Clasificación'), ('regresion', 'Regresión'), ('clustering', 'Agrupamiento (Clustering)'), ('reduccion_dimensional', 'Reducción dimensional'), ('generativo', 'Generativo')], help_text='Tipo de tarea principal', max_length=25)),
                ('familia', models.CharField(choices=[('lineal', 'Lineal'), ('distancia', 'Basado en distancia'), ('kernel', 'Kernel'), ('arbol', 'Árbol'), ('ensemble', 'Conjunto (Ensemble)'), ('red_neuronal', 'Red neuronal'), ('transformer', 'Transformer'), ('proyeccion', 'Proyección (PCA)')], help_text='Familia/algoritmo', max_length=20)),
                ('modalidad', models.CharField(choices=[('tabular', 'Tabular'), ('texto', 'Texto'), ('vision', 'Visión')], default='tabular', help_text='Modalidad de datos típica', max_length=15)),
                ('requiere_escalado', models.BooleanField(default=False, help_text='¿Requiere escalado de características?')),
                ('usa_alpha', models.BooleanField(default=False, help_text='¿Usa parámetro de regularización α (Ridge/Lasso, etc.)?')),
                ('usa_kernel', models.BooleanField(default=False, help_text='¿Usa kernel (SVM, etc.)?')),
                ('anio_inventado', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Año aproximado de invención/publicación', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=200)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='appmodelosIA.modelo')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('modelo', 'nombre')},
            },
        ),
    ]
