# Generated by Django 5.2.7 on 2025-11-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodelosIA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametro',
            name='modelo',
        ),
        migrations.AddField(
            model_name='parametro',
            name='modelo',
            field=models.ManyToManyField(related_name='parametros', to='appmodelosIA.modelo'),
        ),
    ]
