# Generated by Django 5.2.7 on 2025-11-27 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodelosIA', '0002_dataset_modelo_cantidad_votos_modelo_rating_promedio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('tipo_tarea', models.CharField(choices=[('clasificacion', 'Clasificación'), ('regresion', 'Regresión'), ('clustering', 'Clustering'), ('reduccion', 'Reducción Dimensional')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MLDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('tipo_tarea', models.CharField(choices=[('clasificacion', 'Clasificación'), ('regresion', 'Regresión')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MLParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('tipo_dato', models.CharField(choices=[('str', 'Texto'), ('int', 'Entero'), ('float', 'Decimal'), ('bool', 'Booleano')], default='int', max_length=10)),
                ('algoritmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_parametros', to='appmodelosIA.mlalgorithm')),
            ],
        ),
    ]
